### PR TITLE
Minor change

### PR DESCRIPTION
**Pull request by tghosth**
Apologies if you deliberately didn't merge this change, I wasn't sure whether you had missed it or just didn't want to. Just in case of the former, I have raised a new PR.

I have added a comment about pbwatcher. pbwatcher was last updated 3 years ago. I'm not sure if it is supported on iOS 8 but it was not working on my iOS 9 device at all. The pbwatcher application just exits saying "Killed: 9".

### CODE REVIEW

**Comment by marco-lancini** [comment]
Hi @tghosth, can you please check again?
I was able to successfully run pbwatcher on an device running iOS  9

**Comment by tghosth** [comment]
Hi @marco-lancini, thanks for checking. I have double checked and it still doesn't work for me. I have tried just running pbwatcher and also running the command that needle uses (pbwatcher 5 &> /var/root/needle/pbwatcher) and both just exit with Killed: 9.

Were you testing on a 32bit device? I am testing on 64bit (iPhone 6).

**Comment by tghosth** [comment]
Hi @marco-lancini,

I was experimenting with this and I discovered that changing the command to `./pbwatcher 5` allows the program to run.

Can you make it worth using both `pbwatcher 5` and `./pbwatcher 5`?

However, as per my question [here ](https://github.com/dmayer/pbwatcher/issues/1) it doesnt seem to return any content.

**Comment by tghosth** [comment]
Hi @marco-lancini,

I was playing with this more and eventually when I deleted pbwatcher from /usr/bin and let needle recopy it, it started running!

However, as per my question [here ](https://github.com/dmayer/pbwatcher/issues/1) it doesnt seem to return any content.

**Comment by brajbong** [comment]
@tghosth @marco-lancini  I know this issue is closed and marked as invalid, but pbwatcher does not return me any content- running iOS9.3. Anyone else facing this issue still?

**Comment by tghosth** [comment]
No sorry, I was never able to get this running

**Pull request closed without merging**
